### ISSUE TITLE
Problem: Deletion via Storage Service doesn't update deletion status in AM

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica-storage-service#344] opened 2018-03-27 10:34 UTC
**Expected behaviour**

A deleted AIP whether done via the dashboard or the storage service does not show up in the Archivematica dashboard.

**Current behaviour**

Archivematica will still show an AIP deleted via the storage service as `Stored`

**Steps to reproduce**

To recreate, create a deletion request in the storage service and approve it. E.g.
```
archivematica-storage-service_1  | MIME-Version: 1.0
archivematica-storage-service_1  | Content-Type: text/plain; charset="utf-8"
archivematica-storage-service_1  | Content-Transfer-Encoding: 7bit
archivematica-storage-service_1  | Subject: Deletion request for package 5436df46-f23b-4428-8118-bbadd7078737
archivematica-storage-service_1  | From: webmaster@localhost
archivematica-storage-service_1  | To: test@test.com
archivematica-storage-service_1  | Date: Tue, 27 Mar 2018 10:04:41 -0000
archivematica-storage-service_1  | Message-ID: <20180327100441.10.337@1ecfba7d34a8>
archivematica-storage-service_1  | 
archivematica-storage-service_1  | A package deletion request was received:
archivematica-storage-service_1  | 
archivematica-storage-service_1  | Pipeline UUID: ed39ec4a-2039-4e36-b1db-245b67e66fa1
archivematica-storage-service_1  | Package UUID: 5436df46-f23b-4428-8118-bbadd7078737
archivematica-storage-service_1  | Package location: /var/archivematica/sharedDirectory/www/AIPsStore/5436/df46/f23b/4428/8118/bbad/d707/8737/status_1-5436df46-f23b-4428-8118-bbadd7078737.7z
```
Then look at the Archivematica dashboard:
![image](https://user-images.githubusercontent.com/1880412/37962312-32563f28-3217-11e8-8175-51233935c88e.png)

**Your environment (version of Archivematica, OS version, etc)**

Storage service `qa/0.14.x` 

**Additional context**

The workaround is of course to use the Dashboard for deletions. If you delete via the Archivematica dashboard you will see deletion happen in two stages:

* Status: Deletion requested
* Once verified via the Storage Service, the dashboard can be refreshed and the package is gone

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment] 2018-03-29 03:55
Workaround: A mechanism to recreate the elastic search index again (in Archivematica) if this does happen/becomes unbearable: https://github.com/artefactual/archivematica/pull/1028

**Comment by tw4l** [comment] 2020-07-28 20:51
Closed as a duplicate of https://github.com/archivematica/Issues/issues/1189, which extends this issue to transfers in the Backlog tab in addition to AIPs in Archival Storage.

This issue is fixed in PR https://github.com/artefactual/archivematica/pull/1611, which adds a checking routine to the Archival Storage tab in Archivematica that removes deleted AIPs from the `aips` index (and, consequently, the Archival Storage tab), regardless of whether the deletion was initiated from Archivematica or the Storage Service.

**Closed as completed by tw4l** 2020-07-28 20:51 UTC
Labels: Type: feature
